[sdk] add Simplicity SDK for Series 2+ parts
Update PAL

diff --git a/script/build b/script/build
--- a/script/build
+++ b/script/build
@@ -29,7 +29,7 @@
 
 # ==============================================================================
 # Bash definitions
-
+# ==============================================================================
 if [[ -n ${BASH_SOURCE[0]} ]]; then
     script_path="${BASH_SOURCE[0]}"
 else
@@ -37,8 +37,10 @@ else
 fi
 script_dir="$(realpath "$(dirname "${script_path}")")"
 repo_dir="$(dirname "${script_dir}")"
-gsdk_dir="${repo_dir}/third_party/silabs/gecko_sdk"
 
+
+
+# ==============================================================================
 # shellcheck source=script/efr32-definitions
 source "${repo_dir}/script/efr32-definitions"
 
@@ -49,36 +51,54 @@ set -euxo pipefail
 
 # ==============================================================================
 # Pre-build checks
-
-set +x
-echo "========================================================================================================="
-echo "Check if the Git LFS package is installed"
-echo "========================================================================================================="
-set -x
-if ! git lfs >/dev/null; then
+# ==============================================================================
+# Initialize the Silicon Labs SDK
+# This function initializes the Silicon Labs SDK submodule and checks if the platform is supported
+# Arguments:
+#   $1: The board name
+# Returns:
+#   None
+init_silabs_sdk()
+{
     set +x
-    echo "ERROR: Git LFS is not installed"
-    echo
-    echo "Please run './script/bootstrap packages'" to install it
-    exit 3
-fi
+    echo "========================================================================================================="
+    echo "Ensure SDK submodule has been initialized"
+    echo "========================================================================================================="
+    set -x
+    # Skip LFS files for now. They will be pulled in init_silabs_sdk_lfs()
+    GIT_LFS_SKIP_SMUDGE=true git submodule update --init "${sdk_dir}"
 
-set +x
-echo "========================================================================================================="
-echo "Ensure Git LFS has been initialized for the GSDK"
-echo "========================================================================================================="
-set -x
-if [ ! -f "$(git -C "${gsdk_dir}" rev-parse --git-dir)/hooks/pre-push" ]; then
-    git -C "${gsdk_dir}" lfs install
-fi
+    set +x
+    echo "========================================================================================================="
+    echo "Check if the Git LFS package is installed"
+    echo "========================================================================================================="
+    set -x
+    if ! git lfs >/dev/null; then
+        set +x
+        echo "ERROR: Git LFS is not installed"
+        echo
+        echo "Please run './script/bootstrap packages'" to install it
+        exit 3
+    fi
 
-set +x
-echo "========================================================================================================="
-echo "Ensure GSDK submodule has been initialized and LFS objects have been pulled"
-echo "========================================================================================================="
-set -x
-git submodule update --init "${gsdk_dir}"
-git -C "${gsdk_dir}" lfs pull
+    set +x
+    echo "========================================================================================================="
+    echo "Ensure Git LFS has been initialized for the SDK"
+    echo "========================================================================================================="
+    set -x
+    if [ ! -f "$(git -C "${sdk_dir}" rev-parse --git-dir)/hooks/pre-push" ]; then
+        git -C "${sdk_dir}" lfs install
+    fi
+
+    set +x
+    echo "========================================================================================================="
+    echo "Ensure LFS objects have been pulled"
+    echo "========================================================================================================="
+    set -x
+
+    # TODO: Add .lfsconfig lines to only fetch the necessary files
+    git -C "${sdk_dir}" lfs pull
+}
 
 # ==============================================================================
 OT_CMAKE_NINJA_TARGET=${OT_CMAKE_NINJA_TARGET-}
@@ -281,20 +301,28 @@ main()
         shift
     fi
 
-    platform=$(efr32_get_platform "${board}")
+    # Check if a platform can be found for a given board in Simplicity SDK
+    platform=$(efr32_get_platform "${board}" "${sisdk_dir}")
+
+    # Check if the platform is supported
     efr32_check_platform "${platform}" || die "Unsupported platform ${platform}"
+
+    set +x
+    echo "========================================================================================================="
+    echo "Using Simplicity SDK for board ${board} (${platform})"
+    echo "========================================================================================================="
+    set -x
+    # Initialize the SDK
+    init_silabs_sdk "${board}"
 
     local options=("${OT_OPTIONS[@]}")
 
     options+=("-DCMAKE_TOOLCHAIN_FILE=src/${platform}/arm-none-eabi.cmake")
 
+    # Set default OT_CMAKE_NINJA_TARGET based on platform
     if [ -z "${OT_CMAKE_NINJA_TARGET}" ]; then
         case "${platform}" in
-            efr32mg1)
-                OT_CMAKE_NINJA_TARGET=("ot-rcp-uart")
-                skip_silabs_apps=true
-                ;;
-            efr32mg12 | efr32mg13 | efr32mg21 | efr32mg24)
+            efr32mg2*)
                 OT_CMAKE_NINJA_TARGET=("ot-rcp-uart" "ot-rcp-spi" "ot-cli-ftd" "ot-cli-mtd" "ot-ncp-ftd" "ot-ncp-mtd")
                 ;;
         esac
diff --git a/script/efr32-definitions b/script/efr32-definitions
--- a/script/efr32-definitions
+++ b/script/efr32-definitions
@@ -41,10 +41,6 @@ if [ -z ${repo_dir+x} ]; then
     script_dir="$(realpath "$(dirname "${script_path}")")"
     repo_dir="$(dirname "${script_dir}")"
 fi
-# Check if gsdk_dir is defined
-if [ -z ${gsdk_dir+x} ]; then
-    gsdk_dir="${repo_dir}/third_party/silabs/gecko_sdk"
-fi
 
 efr32_device_regex=""
 efr32_device_regex+="\(efr32\)*"                               # Group 1 - efr32 (optional)
@@ -60,23 +56,36 @@ efr32_device_regex+=".*"                                       # Rest of line
 readonly efr32_device_regex
 
 # ==============================================================================
+# SDKs
+# ==============================================================================
+# Simplicity SDK
+sisdk_dir="${repo_dir}/third_party/silabs/simplicity_sdk"
+readonly sisdk_dir
 
+# SDK directory to use
+sdk_dir="${sisdk_dir}"
+
+# ==============================================================================
 efr32_get_board_slcc()
 {
     local -r \
         doc="Gets the latest revision .slcc file for a efr32 board"
     #
     # Arg $1 -- efr32 board
-    if [ $# -ne 1 ] || [ -z "$1" ]; then
+    # Arg $2 -- SDK directory (optional)
+    if [ $# -lt 1 ] || [ -z "$1" ]; then
         printf "%s\n\nUsage:\n\t%s <efr32_board> \n" "${doc}" "${FUNCNAME[0]}" >&2
         return 1
     fi
-    local board=$1
+
+    # Default to existing values if not provided as arguments
+    local board=${1:-${board:?}}
+    local sdk_dir=${2:-${sdk_dir:?}}
 
     # Find component file for latest revision of board
     local board_slcc
     board_slcc=$(
-        find "${gsdk_dir}"/hardware/board/component -type f \( -name "${board}*" ! -name '*_support.slcc' \) \
+        find "${sdk_dir}"/hardware/board/component -type f \( -name "${board}*" ! -name '*_support.slcc' \) \
             | sort --version-sort \
             | tail -n 1
     )
@@ -85,7 +94,19 @@ efr32_get_board_slcc()
 
 efr32_get_platform()
 {
-    local board=${board-$1}
+    local -r \
+        doc="Gets the platform for a efr32 board"
+    #
+    # Arg $1 -- efr32 board (optional)
+    # Arg $2 -- SDK directory (optional)
+    if [ $# -gt 2 ]; then
+        printf "%s\n\nUsage:\n\t%s <efr32_board> \n" "${doc}" "${FUNCNAME[0]}" >&2
+        return 1
+    fi
+
+    # Default to existing values if not provided as arguments
+    local board=${1:-${board:?}}
+    local sdk_dir=${2:-${sdk_dir:?}}
 
     # Find component file for latest revision of board
     local board_slcc
@@ -99,16 +120,12 @@ efr32_get_platform()
             | head -n 1
     )
 
-    if [ -z "${platform}" ]; then
-        echo "Error parsing platform"
-        exit 3
-    fi
-
     echo "${platform}"
 }
 
 efr32_get_platforms()
 {
+    # TODO:
     local platform_dir="$repo_dir/src" \
         && find "$platform_dir" -type d -name '*efr32*' -exec basename {} \; | sort
 }
@@ -130,8 +147,8 @@ efr32_check_platform()
 
     if ! $match; then
         set +x
-        printf "\n\nERROR: Invalid platform\n" >&2
-        printf "Valid platforms:\n" >&2
+        printf "\n\nERROR: Unsupported platform\n" >&2
+        printf "Supported platforms:\n" >&2
         for platform in $(efr32_get_platforms); do
             printf " - %s\n" "${platform}" >&2
         done
