Make pretty and fix broken markdown links

diff --git a/script/efr32-definitions b/script/efr32-definitions
--- a/script/efr32-definitions
+++ b/script/efr32-definitions
@@ -6,11 +6,11 @@ repo_dir="$(dirname "$script_dir")"
 efr32_get_platforms()
 {
     if [ $# -ne 0 ]; then
-        printf "Gets a list of platforms\n\nUsage: %s\n" $(basename $0) >&2
+        printf "Gets a list of platforms\n\nUsage: %s\n" "$(basename "$0")" >&2
         return 1
     fi
 
-    cd $repo_dir/src/
+    cd "$repo_dir"/src/ || return
     local platforms=(*efr32*/)
     echo "${platforms[@]%/}"
 }
@@ -20,16 +20,25 @@ efr32_check_platform()
     # Checks if a value is a valid efr32 platform
     #
     # Arg $1 -- value
-    if [ -z $1 ] || [ $# -ne 1 ]; then
-        printf "Checks if a value is a valid efr32 platform\n\nUsage: %s <value> \n" $(basename $0) >&2
+    if [ -z "$1" ] || [ $# -ne 1 ]; then
+        printf "Checks if a value is a valid efr32 platform\n\nUsage: %s <value> \n" "$(basename "$0")" >&2
         return 1
     fi
 
+    local match=false
     local platform="$1"
-    local platforms=$(efr32_get_platforms)
+    local platforms=()
+    while IFS='' read -r line; do platforms+=("$line"); done < <(efr32_get_platforms)
 
-    if [[ ! " ${platforms[@]} " =~ " $platform " ]]; then
-        printf "ERROR: Invalid platform\nValid platforms:   ${platforms[@]}\n" >&2
+    for efr32_platform in ${platforms[@]}; do
+        if [[ $efr32_platform == "$platform" ]]; then
+            match=true
+            break
+        fi
+    done
+
+    if ! $match; then
+        printf "ERROR: Invalid platform\nValid platforms:   %s\n" "${platforms[*]}" >&2
         return 2
     fi
     return 0
@@ -40,8 +49,8 @@ efr32_get_boards()
     # Gets a list of boards for a given platform
     #
     # Arg $1 -- efr32 platform
-    if [ -z $1 ] || [ $# -ne 1 ]; then
-        printf "Gets a list of boards for a given platform\n\nUsage: %s <efr32_platform> \n" $(basename $0) >&2
+    if [ -z "$1" ] || [ $# -ne 1 ]; then
+        printf "Gets a list of boards for a given platform\n\nUsage: %s <efr32_platform> \n" "$(basename "$0")" >&2
         return 1
     fi
 
@@ -49,7 +58,7 @@ efr32_get_boards()
 
     efr32_check_platform "$platform" \
         && local platform_dir="$repo_dir/src/$platform" \
-        && find $platform_dir -type d -name 'brd*' -exec basename {} \; | sort
+        && find "$platform_dir" -type d -name 'brd*' -exec basename {} \; | sort
 }
 
 efr32_get_jlink_device()
@@ -57,13 +66,13 @@ efr32_get_jlink_device()
     # Gets the J-Link device type for a efr32 platform
     #
     # Arg $1 -- efr32 platform
-    if [ -z $1 ] || [ $# -ne 1 ]; then
-        printf "Gets the J-Link device type for a efr32 platform\n\nUsage: %s <efr32_platform> \n" $(basename $0) >&2
+    if [ -z "$1" ] || [ $# -ne 1 ]; then
+        printf "Gets the J-Link device type for a efr32 platform\n\nUsage: %s <efr32_platform> \n" "$(basename "$0")" >&2
         return 1
     fi
 
     local platform="$1"
-    efr32_check_platform $platform \
+    efr32_check_platform "$platform" \
         && case $platform in
             "efr32mg1")
                 echo "EFR32MG1PxxxF256"
