[sdk] update to Simplicity SDK v2024.6.0 (#918)
* [sdk] add Simplicity SDK for Series 2+ parts

Update PAL

* [slc] remove usage of daemon mode

Using daemon mode causes issues when developing SLC components

* [slc] add `ot_efr32` version of `ot_headers`

As part of SBOM work, openthread headers were pulled out of SLC components
which referenced mostly Silabs code and consolidated into the `ot_headers`
component. A requirement for `ot_headers` was then added to affected
components.

This requirement causes ALL OpenThread headers to be added to any component
which previously only required a subset of the headers.

In the context of ot-efr32 builds, this causes SLC generation failures as the
CMake platform library definitions will now reference all openthread headers in
`ot_headers`, which may or may not match up (ex. deleted) with the version of
OpenThread checked out in the `openthread` submodule in ot-efr32.

This commit adds an ot-efr32 version of `ot_headers` which fixes the issue by
pulling in only required headers instead of all headers in the `simplicity_sdk`
version of `ot_headers`.

* [script] misc. script improvements

diff --git a/script/efr32-definitions b/script/efr32-definitions
--- a/script/efr32-definitions
+++ b/script/efr32-definitions
@@ -29,6 +29,7 @@
 
 # ==============================================================================
 # Bash definitions
+# ==============================================================================
 
 if [[ -n ${BASH_SOURCE[0]} ]]; then
     script_path="${BASH_SOURCE[0]}"
@@ -41,42 +42,54 @@ if [ -z ${repo_dir+x} ]; then
     script_dir="$(realpath "$(dirname "${script_path}")")"
     repo_dir="$(dirname "${script_dir}")"
 fi
-# Check if gsdk_dir is defined
-if [ -z ${gsdk_dir+x} ]; then
-    gsdk_dir="${repo_dir}/third_party/silabs/gecko_sdk"
+
+# Define the regex for efr32 devices if not already defined
+if [ -z ${efr32_device_regex+x} ]; then
+    efr32_device_regex=""
+    efr32_device_regex+="\(efr32\)*"                               # Group 1 - efr32 (optional)
+    efr32_device_regex+="\([[:alpha:]]\{2\}\)"                     # Group 2 - mg, bg, xg (product line)
+    efr32_device_regex+="\(m*\)"                                   # Group 3 - m (optional, modules only)
+    efr32_device_regex+="\([[:digit:]]\{1,2\}\)[[:digit:]]\{0,1\}" # Group 4 - 1, 12, 13, 21, 24, 210, 240 etc (series and configuration)
+    efr32_device_regex+="\([[:alpha:]]\{1\}\)"                     # Group 5 - a, b, c, p, v (revision)
+    efr32_device_regex+="\([[:alpha:]]\{0,1\}[[:digit:]]\{1,3\}\)" # Group 6 - xxx, a32, 032
+    efr32_device_regex+="\(f[[:digit:]]\{1,\}\)*"                  # Group 7 - fXXX (flash size)
+    efr32_device_regex+="\([[:alpha:]]\{2,3\}\)*"                  # Group 8 - im, gl, gm, jia, vna, etc
+    efr32_device_regex+="\(f[[:digit:]]\{1,\}\)*"                  # Group 9 - 32, 40, 48, 68, 125
+    efr32_device_regex+=".*"                                       # Rest of line
+    readonly efr32_device_regex
 fi
 
-efr32_device_regex=""
-efr32_device_regex+="\(efr32\)*"                               # Group 1 - efr32 (optional)
-efr32_device_regex+="\([[:alpha:]]\{2\}\)"                     # Group 2 - mg, bg, xg (product line)
-efr32_device_regex+="\(m*\)"                                   # Group 3 - m (optional, modules only)
-efr32_device_regex+="\([[:digit:]]\{1,2\}\)[[:digit:]]\{0,1\}" # Group 4 - 1, 12, 13, 21, 24, 210, 240 etc (series and configuration)
-efr32_device_regex+="\([[:alpha:]]\{1\}\)"                     # Group 5 - a, b, c, p, v (revision)
-efr32_device_regex+="\([[:alpha:]]\{0,1\}[[:digit:]]\{1,3\}\)" # Group 6 - xxx, a32, 032
-efr32_device_regex+="\(f[[:digit:]]\{1,\}\)*"                  # Group 7 - fXXX (flash size)
-efr32_device_regex+="\([[:alpha:]]\{2,3\}\)*"                  # Group 8 - im, gl, gm, jia, vna, etc
-efr32_device_regex+="\(f[[:digit:]]\{1,\}\)*"                  # Group 9 - 32, 40, 48, 68, 125
-efr32_device_regex+=".*"                                       # Rest of line
-readonly efr32_device_regex
+# ==============================================================================
+# SDKs
+# ==============================================================================
+# Simplicity SDK
+sisdk_dir="${repo_dir}/third_party/silabs/simplicity_sdk"
+readonly sisdk_dir
+
+# SDK directory to use
+sdk_dir="${sisdk_dir}"
 
 # ==============================================================================
-
 efr32_get_board_slcc()
 {
     local -r \
         doc="Gets the latest revision .slcc file for a efr32 board"
     #
-    # Arg $1 -- efr32 board
-    if [ $# -ne 1 ] || [ -z "$1" ]; then
-        printf "%s\n\nUsage:\n\t%s <efr32_board> \n" "${doc}" "${FUNCNAME[0]}" >&2
+    # Arg $1 -- efr32 board (optional) (default: $board)
+    # Arg $2 -- SDK directory (optional) (default: $sdk_dir)
+    if [ $# -lt 1 ] || [ -z "$1" ]; then
+        printf "%s\n\nUsage:\n\t%s [efr32_board] \n" "${doc}" "${FUNCNAME[0]}" >&2
         return 1
     fi
-    local board=$1
+
+    # Default to existing values if not provided as arguments
+    local board=${1:-${board:?}}
+    local sdk_dir=${2:-${sdk_dir:?}}
 
     # Find component file for latest revision of board
     local board_slcc
     board_slcc=$(
-        find "${gsdk_dir}"/hardware/board/component -type f \( -name "${board}*" ! -name '*_support.slcc' \) \
+        find "${sdk_dir}"/hardware/board/component -type f \( -name "${board}*" ! -name '*_support.slcc' \) \
             | sort --version-sort \
             | tail -n 1
     )
@@ -85,7 +98,19 @@ efr32_get_board_slcc()
 
 efr32_get_platform()
 {
-    local board=${board-$1}
+    local -r \
+        doc="Gets the platform for a efr32 board"
+    #
+    # Arg $1 -- efr32 board (optional) (default: $board)
+    # Arg $2 -- SDK directory (optional) (default: $sdk_dir)
+    if [ $# -gt 2 ]; then
+        printf "%s\n\nUsage:\n\t%s <efr32_board> \n" "${doc}" "${FUNCNAME[0]}" >&2
+        return 1
+    fi
+
+    # Default to existing values if not provided as arguments
+    local board=${1:-${board:?}}
+    local sdk_dir=${2:-${sdk_dir:?}}
 
     # Find component file for latest revision of board
     local board_slcc
@@ -99,11 +124,6 @@ efr32_get_platform()
             | head -n 1
     )
 
-    if [ -z "${platform}" ]; then
-        echo "Error parsing platform"
-        exit 3
-    fi
-
     echo "${platform}"
 }
 
@@ -115,9 +135,15 @@ efr32_get_platforms()
 
 efr32_check_platform()
 {
-    # Checks if a value is a valid efr32 platform
+    local -r \
+        doc="Checks if a value is a valid efr32 platform"
     #
-    # Arg $1 -- value
+    # Arg $1 -- platform
+    if [ $# -ne 1 ]; then
+        printf "%s\n\nUsage:\n\t%s <platform> \n" "${doc}" "${FUNCNAME[0]}" >&2
+        return 1
+    fi
+
     local match=false
     local platform="${1?}"
 
@@ -128,10 +154,11 @@ efr32_check_platform()
         fi
     done
 
+    # if no match, print error message
     if ! $match; then
         set +x
-        printf "\n\nERROR: Invalid platform\n" >&2
-        printf "Valid platforms:\n" >&2
+        printf "\n\nERROR: Unsupported platform\n" >&2
+        printf "Supported platforms:\n" >&2
         for platform in $(efr32_get_platforms); do
             printf " - %s\n" "${platform}" >&2
         done
