[script] use new trusted public URL to download slc_cli zip files (#1196)
Additionally add some slc debug logging.

diff --git a/script/generate b/script/generate
--- a/script/generate
+++ b/script/generate
@@ -252,7 +252,13 @@ generate()
 
 cleanup()
 {
-    # Placeholder for any cleanup tasks
+    # print out slc error logs if any
+    if [ $? -ne 0 ]; then
+        echo "Checking slc logs..."
+        find "${SLC_INSTALL_DIR}"/slc_cli/bin/slc-cli/configuration/ -type f -name "*.log" -exec cat {} +
+    fi
+
+    # Placeholder for any other cleanup tasks
     :
 }
 
