[slc][examples] add `ot-efr32` and `example_vendor` slc extensions (#549)
This commit adds an SLC extension for `ot-efr32` and provides an
example implementation of an SLC extension for vendors building with
ot-efr32 who may want to extend their builds with additional sources
and/or customizations.

As of now, the `ot-efr32` extension doesn't provide any additional
components, but some will be added in the future.

diff --git a/examples/example_vendor_slc_extension/script/build b/examples/example_vendor_slc_extension/script/build
--- a/examples/example_vendor_slc_extension/script/build
+++ b/examples/example_vendor_slc_extension/script/build
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-#  Copyright (c) 2021, The OpenThread Authors.
+#  Copyright (c) 2023, The OpenThread Authors.
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -27,33 +27,59 @@
 #  POSSIBILITY OF SUCH DAMAGE.
 #
 
-set -euxo pipefail
+repo_dir="$(git rev-parse --show-toplevel)"
+
+# shellcheck source=script/util
+source "${repo_dir}/script/util"
+
+set -exuo pipefail
+# ==============================================================================
+# Bash definitions
+if [[ -n ${BASH_SOURCE[0]} ]]; then
+    script_path="${BASH_SOURCE[0]}"
+else
+    script_path="$0"
+fi
+
+extension_script_dir="$(realpath "$(dirname "${script_path}")")"
+extension_dir="$(dirname "${extension_script_dir}")"
 
 repo_dir="$(git rev-parse --show-toplevel)"
 
-install_slc_cli()
+cleanup()
 {
-    [ -n "${SLC_INSTALL_DIR-}" ] || SLC_INSTALL_DIR="${repo_dir}/slc"
-
-    # Install slc-cli
-    local os_type
-    if [[ $OSTYPE == "linux"* ]]; then
-        os_type="linux"
-    elif [[ $OSTYPE == "darwin"* ]]; then
-        os_type="mac"
-    fi
-
-    local zip_url="https://www.silabs.com/documents/login/software/slc_cli_${os_type}.zip"
-    pushd "${SLC_INSTALL_DIR}"
-    local zip_path="./slc_cli.zip"
-    wget "${zip_url}" -O "${zip_path}"
-    unzip -q -o "${zip_path}" -d "$(dirname ${zip_path})"
-    popd
+    # Placeholder for any cleanup tasks
+    :
 }
+
+trap cleanup EXIT
 
 main()
 {
-    install_slc_cli
+    local extension_abs_path=""
+    case "${extension_dir}" in
+        /*)
+            # absolute path
+            extension_abs_path="${extension_dir}"
+            ;;
+        *)
+            # relative path
+            extension_abs_path=$(realpath "$(pwd)/${extension_dir}")
+            if [ ! -d "${extension_abs_path}" ]; then
+                set +x
+                echo "extension_dir=${extension_dir}"
+                echo "extension_abs_path=${extension_abs_path}"
+                echo "ERROR: '${extension_abs_path}' does not exist"
+                exit 5
+            fi
+            ;;
+    esac
+
+    # Set the VENDOR_EXTENSION env variable for the ${repo_dir}/script/generate to pull in the vendor extension
+    export VENDOR_EXTENSION="${extension_abs_path}"
+
+    # Build
+    "${repo_dir}/script/build" "$@"
 }
 
-main
+main "$@"
diff --git a/script/util b/script/util
--- a/script/util
+++ b/script/util
@@ -34,3 +34,72 @@ contains()
     IFS=" " read -r -a list <<<"$@"
     echo "${list[@]}" | grep -w -q -E "$search_term"
 }
+
+create_srec()
+{
+    local executable_flag
+
+    if [ "$(uname)" = 'Linux' ]; then
+        executable_flag=(-executable)
+    elif [ "$(uname)" = 'Darwin' ]; then
+        executable_flag=(-perm +111)
+    fi
+
+    find "$1" -type f "${executable_flag[@]}" -not -name '*.*' -exec arm-none-eabi-objcopy -O srec {} {}.s37 \; -exec ls -alh {} {}.s37 \;
+}
+
+die()
+{
+    echo " ** ERROR: $1"
+    exit 1
+}
+
+parse_configuration()
+{
+    local extension_dir="${extension_dir-.}"
+    local config_yml=""
+
+    if [ $# -eq 0 ]; then
+        # No args passed. Use defaults
+        config_yml="${extension_dir}/config.yml"
+    elif [ $# -eq 1 ]; then
+        extension_dir=$1
+        config_yml="${extension_dir}/config.yml"
+    elif [ $# -eq 2 ]; then
+        extension_dir=$1
+        config_yml=$2
+    else
+        echo "ERROR: Too many args"
+        echo "usage: parse_configuration [extension_dir] [config_yml]"
+        return 1
+    fi
+
+    # Check that ${config_yml} exists
+    if [ ! -f "${config_yml}" ]; then
+        echo "ERROR: '${config_yml}' not found"
+        return 2
+    fi
+
+    # Temporarily disable 'set -e'
+    # This will allow configuration files that only define a subset of "*_slcp" keys
+    old_setting=${-//[^e]/}
+    set +e
+    # grep raw values from the configuration file
+    rcp_uart_slcp="$(grep -oP 'rcp_uart_slcp: \K(.*)' "${config_yml}")"
+    rcp_spi_slcp="$(grep -oP 'rcp_spi_slcp: \K(.*)' "${config_yml}")"
+    soc_slcp="$(grep -oP 'soc_slcp: \K(.*)' "${config_yml}")"
+    board="$(grep -oP 'board: \K(.*)' "${config_yml}")"
+
+    # Strip quotes
+    rcp_uart_slcp=$(eval echo "${rcp_uart_slcp}")
+    rcp_spi_slcp=$(eval echo "${rcp_spi_slcp}")
+    soc_slcp=$(eval echo "${soc_slcp}")
+    board=$(eval echo "${board}")
+
+    # Make paths relative to extension_dir, stripping leading './'
+    rcp_uart_slcp="${extension_dir}/${rcp_uart_slcp#./}"
+    rcp_spi_slcp="${extension_dir}/${rcp_spi_slcp#./}"
+    soc_slcp="${extension_dir}/${soc_slcp#./}"
+    if [[ -n $old_setting ]]; then set -e; else set +e; fi
+
+}
